### ISSUE TITLE
Create extension foundation

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/WikibaseFacetedSearch#1]
AC:

* Correct ASCII art in the commit message :)
* MediaWiki extension shows up on Special:Version
* i18n present
* depends on Wikibase Repository, WikibaseCirrusSearch, CirrusSearch

Optional (can be follow up):

* Our latest local CI setup (PHPUnit, PHPCS, PHPStan)
    * With WikibaseCirrusSearch and dependencies (includes ElasticSearch service) 
* Our latest GH Actions config
    * With WikibaseCirrusSearch and dependencies (includes ElasticSearch service)

**Comment by malberts** [comment]
Added in https://github.com/ProfessionalWiki/WikibaseFacetedSearch/commit/888ba9fc108a9d50b02bbb286229c65731e1a3b3 (plus small follow-ups).

![Screenshot_20241127_020749](https://github.com/user-attachments/assets/11b8b18e-699e-47c0-83e0-4623f73cd3cb)

Includes basic CI, but still need to install Wikibase and ElasticSearch.
