### ISSUE TITLE
Rewrite search result link to page in sitelinks

### ISSUE THREAD

**Issue by malberts** [ProfessionalWiki/WikibaseFacetedSearch#4]
Partial follow-up to #3 

Wikibase items in the search results need to link to a wiki page based on a specific sitelink.

**Comment by JeroenDeDauw** [comment]
We will need to specify the "site code" to Wikibase, which we need to have in our configuration.

I expect something like this to work

```php
Title::newFromText( SiteLinkLookup::getSiteLinksForItem( new ItemId( 'Q123' ) )[$siteCodeFromOurConfig]->getPageName() )
```

* Need to get SiteLinkLookup instance
* Need to ensure the correct namesaces title is constructed when getPageName returns `Person:172415`
