### ISSUE TITLE
Find how to execute Elastic queries within MediaWiki PHP

### ISSUE THREAD

**Issue by malberts** [ProfessionalWiki/WikibaseFacetedSearch#5]
Additional ElasticSearch queries needs to be done to get the facet values and counts for the current search result.

Determine how this can be done via:
* CirrusSearch extension; or
* Elastica extension; or
* ruflin/elastica dependency

**Comment by JeroenDeDauw** [comment]
Merging into https://github.com/ProfessionalWiki/WikibaseFacetedSearch/issues/10

**Comment by JeroenDeDauw** [comment]
WikibaseCirrusSearch is using some query DSL provided by `ruflin/elastica`. We might need to be able to run complex queries. See the "script" in https://github.com/ProfessionalWiki/WikibaseFacetedSearch/issues/23#issuecomment-2508655267. Perhaps this creates complications or restricts what part of the DSL we use.

**Comment by malberts** [comment]
`ruflin/elastica` supports running raw queries: https://elastica.io/example/raw-json-query.html
